### ISSUE TITLE
Tracker: Code Coverage

### ISSUE THREAD

**Issue by worksofliam** [codefori/vscode-ibmi#2153]
It's time to release code coverage, but this time using the VS Code testing API instead of a custom view.

* https://code.visualstudio.com/api/references/vscode-api#FileCoverage
* Have been told by Connor Peet on Twitter that the API has not been finalized yet. We should wait for this.

VS Code now supports statement coverage, which is exactly what IBM i Code Coverage provides.

* [ ] ability to import zip
* [ ] ability to view zip by file and then statement coverage, including percentage per file
* [ ] consider ways to execute a coverage test from the UI. The only extension allowed the user to define tests in a custom UI. Do we still want this?

**Comment by SanjulaGanepola** [comment]
@worksofliam Thoughts on moving this issue over to the test repo? Could be a good idea to still add support for importing zip files to view in vs code.

**Comment by worksofliam** [comment]
@SanjulaGanepola good deal. Reading and showing the cczip data has a lot of potential.
